### ISSUE TITLE
Instructions for use not included

### ISSUE THREAD

**Issue by AnonymousDapper** [warriordog/MapMaster#2]
I am looking to build a map of a world using VoxelMap and a program like this, but I cannot figure out how to use MapMaster.

**Comment by warriordog** [comment]
@SpoopySaitama 

This tool was never finished, and I haven't touched it in 2 years.  VoxelMap support was iffy, but may still work if VM has not changed the map format.  But if you do want to use it, this is the basic process (You will need to do a lot of work for step 2):

1. Compile MapMaster to a jar with MapMaster.java as the main class
2. Write a config file json that matches the private non-transient fields in MapScript.java.  Sadly I don't remember how to do this, and this is the biggest part.  I tried to find the workspace where I had a config file already written, but I don't have it anymore.  You should be able to generate the file by compiling MapMaster and using MapScript as the main class.  There is an extra main method that is supposed to generate a template file, but I never used it much so it may be missing fields.  It will be a start, however.
3. Place the jar in a folder that contains the zips or folders with the map data
4. Run java -jar MapMaster <config_file_path>

**Comment by AnonymousDapper** [comment]
@warriordog Oh man, that'll be fun. Thanks for the quick reply.

**Comment by warriordog** [comment]
@SpoopySaitama 

Good luck with your project, hopefully you can get this working.  I abandoned it after someone finished the project I was using it for, but it was working before that.  Let me know if you have any questions about the internals or how this works.
